### PR TITLE
#110 Cache & Node 4.2 

### PR DESCRIPTION
**Pull request by gotchazipc**
redis is coming... & we'll move on to node 4.2, as documented. 

- session will be changed to redis, also, after merging this PR

### CODE REVIEW

**Comment by kyungmi** [comment]
@gotchazipc A wrong commit(b0804184a157644f7443bdd8677e37b3c3f1a332) was mixed in this PR. Can you try to rebase your commits?

**Comment by gotchazipc** [comment]
sorry for jshint errors. we may fix the errors later, after merging.

**Comment by wcho** [comment]
Were there any problems fixing jshint error before merging?

**Comment by kyungmi** [comment]
@wcho There were warnings related with ES6 from jshint checker. We are going to fix it with the jenkins server.

**Pull request merged**
