### PR TITLE
[TASK] replace the listDir functionality with `find` command

### PR DESCRIPTION
**Pull request by kyungmi**
[DESC.]
- using `find` command for speeding up recursive file listing
- refactoring `fs-manager.js`
     - separated into `fs-service.js`(access file system) and `Resource.js`(model)
     - remove needless functions
     - clean up some duplicated methods

### CODE REVIEW

**Comment by wcho** [comment]
Is `find` really faster?

**Comment by gotchazipc** [comment]
Seems good. If find command does not make so big performance problems, shorter code is better. 

And.. please use strict mode :)

**Comment by kyungmi** [comment]
@wcho We need to check performance by a point of view of CPU usage.

**Comment by wcho** [comment]
I'm not sure but `find` could be slower due to synchronous fs system calls and process fork overhead. I think current implementation does not suffer from CPU problem.

**Pull request closed without merging**
